/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package me.lessis;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int n_0=0x7f020000;
        public static final int n_1=0x7f020001;
        public static final int n_2=0x7f020002;
        public static final int n_3=0x7f020003;
        public static final int n_4=0x7f020004;
        public static final int n_5=0x7f020005;
        public static final int n_6=0x7f020006;
        public static final int n_7=0x7f020007;
        public static final int n_8=0x7f020008;
        public static final int n_9=0x7f020009;
        public static final int roundcorner=0x7f02000a;
    }
    public static final class id {
        public static final int h_ones=0x7f050001;
        public static final int h_tens=0x7f050000;
        public static final int m_ones=0x7f050004;
        public static final int m_tens=0x7f050003;
        public static final int meridiem=0x7f050005;
        public static final int sep=0x7f050002;
    }
    public static final class layout {
        public static final int clock=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
